FROM ubuntu:16.04

MAINTAINER Konrad Scherer <Konrad.Scherer@windriver.com>

RUN \
    sed -i 's#archive.ubuntu.com#yow-mirror.wrs.com/mirror/ubuntu.com#' /etc/apt/sources.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" -qy install \
      --no-install-recommends python libsasl2-2 libsvn1 libapr1 libcurl3 libexpat1 \
      libsqlite3-0 libuuid1 curl && \
    curl -s -o /bin/dumb-init http://yow-mirror.wrs.com/mirror/dumb-init/dumb-init_1.0.1_amd64 && \
    chmod +x /bin/dumb-init && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd --home-dir /home/wrlbuild --uid 1000 --gid 100 --shell /bin/bash wrlbuild && \
    mkdir /home/wrlbuild && chown -R 1000:100 /home/wrlbuild && \
    echo "wrlbuild ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

ADD wraxl/scheduler.yaml /etc/wraxl_scheduler.yaml

ADD dist/wraxl_scheduler /usr/bin/wraxl_scheduler

# pex unpacks the zip file into /home/wrlbuild/.pex so make the home
# dir a volume to avoid overhead
VOLUME ["/home/wrlbuild"]

ENTRYPOINT ["/bin/dumb-init"]

USER wrlbuild

CMD ["/usr/bin/wraxl_scheduler"]
