FROM ubuntu:wily

MAINTAINER Konrad Scherer <Konrad.Scherer@windriver.com>

RUN \
    sed -i 's#archive.ubuntu.com#yow-mirror.wrs.com/mirror/ubuntu.com#' /etc/apt/sources.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" -qy install --no-install-recommends \
    python libsasl2-2 libsvn1 libapr1 libcurl3 libexpat1 libsqlite3-0 libuuid1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /usr/share/man && \
    rm -rf /usr/share/doc && \
    rm -rf /usr/share/grub2 && \
    rm -rf /usr/share/texmf/fonts && \
    rm -rf /usr/share/texmf/doc

RUN useradd --home-dir /home/wrlbuild --uid 1000 --gid 100 --shell /bin/bash wrlbuild && \
    mkdir /home/wrlbuild && chown -R 1000:100 /home/wrlbuild && \
    echo "wrlbuild ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

ADD wraxl/scheduler.yaml /etc/wraxl_scheduler.yaml

ADD dist/wraxl_scheduler /usr/bin/wraxl_scheduler

# pex unpacks the zip file into /home/wrlbuild/.pex so make the home
# dir a volume to avoid overhead
VOLUME ["/home/wrlbuild"]

USER wrlbuild

ENTRYPOINT ["/usr/bin/wraxl_scheduler"]
