version: '2'
services:
  master:
    image: $REGISTRY:5000/mesos-master:$MESOS_TAG
    ports:
      - "5050:5050"
    environment:
      MESOS_ADVERTISE_IP: $HOSTIP
      MESOS_WORK_DIR: /tmp/mesos
      MESOS_LOG_DIR: /tmp/mesos/log
      MESOS_LOGGING_LEVEL: $LOG_LEVEL
      MESOS_CLUSTER: wraxl
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
    tmpfs:
      - /tmp

  agent:
    image: $REGISTRY:5000/mesos-agent:$MESOS_TAG
    ports:
      - "5051:5051"
    links:
      - "master"
    environment:
      MESOS_MASTER: $HOSTIP:5050
      MESOS_HOSTNAME: $HOST
      MESOS_ISOLATOR: "cgroups/cpu,cgroups/mem"
      MESOS_CONTAINERIZERS: "docker,mesos"
      MESOS_EXECUTOR_REGISTRATION_TIMEOUT: "5mins"
      MESOS_PORT: "5051"
      MESOS_LOG_DIR: /tmp/mesos/log/
      MESOS_LOGGING_LEVEL: $LOG_LEVEL
      MESOS_WORK_DIR: /tmp/mesos
      MESOS_RESOURCES: high:1;mem:20480
      # MESOS_ATTRIBUTES: location:ala
    tmpfs:
      - /tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
