version: '2'
services:
  # Add this file to start the scheduler image
  scheduler:
    image: $REGISTRY:5000/mesos-scheduler:0.25.0
    links:
      - "master"
      - "redis"
    environment:
      MESOS_MASTER: $HOSTIP:5050
      WRAXL_REDIS: $HOSTIP
